version: "3"

services:
  mariadb:
    build: ./requirement/mariadb
    image: mariadb:inception
    container_name: mariadb
    ports:
      - '3306:3306'
    restart: always
    env_file:
      - .env
    networks:
      - docknet
    volumes:
      - db_mariadb:/var/lib/mysql/
  nginx:
    build: ./requirement/nginx
    image: nginx:inception
    container_name: nginx
    env_file:
      - .env
    ports:
      - '443:443'
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - docknet
    volumes:
      - db_wordpress:/var/www/html
  wordpress:
    build: ./requirement/wordpress
    image: wordpress:inception
    container_name: wordpress
    env_file:
      - .env
    ports:
      - '9000:9000'
    restart: always
    depends_on:
      - mariadb
    networks:
      - docknet
    volumes:
      - db_wordpress:/var/www/html
volumes:
  db_wordpress:
    # driver: local
    # driver_opts:
    #   device: ${PWD}/data/db_wordpress
    #   type: none
    #   o: binds
    #   #/home/ababouel/data/db_wordpress
  db_mariadb:
    # driver: local
    # driver_opts:
    #   device: ${PWD}/data/db_mariadb
    #   type: none
    #   o: binds
    #   #/home/ababouel/data/db_mariadb
networks:
  docknet:
    driver: bridge
